about:
  home: http://gitub.com/ESGF/output_viewer
package:
  name: output_viewer
  version: 1.0.8
requirements:
  build:
  - python
  - setuptools
  - requests
  run:
  - python
  - requests
source:
  git_rev: v1.0.8
  git_url: git://github.com/ESGF/output_viewer.git
