package:
  name: output_viewer
  version: 1.0.5

source:
  git_rev: v1.0.5
  git_url: git://github.com/ESGF/output_viewer.git

requirements:
  build:
    - python
    - setuptools
    - requests
  run:
    - python
    - requests

about:
  home:  http://gitub.com/ESGF/output_viewer
