package:
  name: output_viewer
  version: 1.0.1

source:
  git_rev: v1.0.1
  git_url: git://github.com/ESGF/output_viewer.git

build:
  string: beta

requirements:
  build:
    - python
    - setuptools
    - requests
  run:
    - python
    - requests

about:
  home:  http://gitub.com/ESGF/output_viewer
