about:
  home: https://gitub.com/ESGF/output_viewer
build:
  script: python setup.py install
  noarch: python
package:
  name: output_viewer
  version: 1.2.6
requirements:
  build:
  - python {{ python }}
  - setuptools
  - requests
  run:
  - python
  - requests
source:
  git_rev: v1.2.6
  git_url: https://github.com/ESGF/output_viewer.git
