about:
  home: https://gitub.com/ESGF/output_viewer
package:
  name: output_viewer
  version: 1.3.0
requirements:
  build:
  - python {{ python }}
  - setuptools
  - requests
  run:
  - python
  - requests
source:
  git_rev: v1.3.0
  git_url: https://github.com/ESGF/output_viewer.git
