package:
  name: output_viewer
  version: 1.3.0

source:
  git_url: https://github.com/ESGF/output_viewer.git
  git_rev: v1.3.0

requirements:
  build:
    - python {{ python }}
    - setuptools
    - requests

  run:
    - python {{ python }}
    - requests

about:
  home: https://github.com/ESGF/output_viewer
